config/routes.rb
Rails.application.routes.draw do

  resources :registrations

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'welcome/index'

  root 'static_pages#home'

  
  get 'static_pages/aboutus'
  get 'static_pages/contactus'
  post 'static_pages/create'
  get 'password_resets/new'
  get 'password_resets/edit'
  get 'sessions/new'
  post 'categories/search'
  get 'categories/index'

  get 'contact' => 'static_pages#contactus'
  get 'aboutus' => 'static_pages#aboutus'
  post 'contact' => 'static_pages#create'
  post 'results' => 'categories#search'
  get 'results' => 'categories#index'
  resources :categories
  resources :products

  resources :cart do
    collection do
      get 'checkout'
      get 'set'
    end
  end

  resources :users do
    resources :addresses
    resources :orders
  end

  resources :payments

  get 'signup'  => 'users#new'
  get 'account' => 'users#show'
  get 'update' => 'users#edit'

  post "/hook" => "orders#hook"
  post "/users/:user_id/orders/:id" => 'orders#index'

  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  resources :contact, only: [:create]
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home        
    unless Category.where(:name => "New").blank?
    new_cat = Category.find_by(name: "New")
    @new_products = new_cat.products  
    end
    unless Category.where(:name => "Special").blank?
    special_cat = Category.find_by(name: "Special")
    @special_products = special_cat.products      
    end
    
  end

  def aboutus
    @title = "About Us"

  end

  def contactus
    @title = "Contact Us"
  end

  def create
    @message = Message.new(msg_params)

    if @message.valid?
      ContactMailer.contact_email(msg_params).deliver
    else
      @title = "Contact Us"
      render 'contactus'
    end
  end

  private

  def msg_params
    params[:contact].permit(:name, :email, :content)
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/contactus.html.erb
<div class="contact_wrapper">
	<%= form_for :contact, :html => {:role => "form"}, url:   contact_path do |f| %>
	<div style="text-align: center; width: 100%">
		<% if @message != nil && @message.errors.any? %>
		<div class="error_wrapper row">
			<div class="error_inner  bg-warning text-danger col-sm-4 col-sm-offset-4" >
				<ul style="text-align: left">
					<% @message.errors.full_messages.each do |msg| %>
					<li>
						<%= msg %>
					</li>
					<% end %>
				</ul>
			</div>
		</div>

		<% end %>

	</div>
	<div class="row">
		<div class="col-sm-4 col-sm-offset-4 input_wrapper">
			<span class="glyphicon glyphicon-user"></span> <span>Name:</span>
			<%= f.text_field :name%>
		</div>
	</div>
	<div class="row">
		<div class="form-group col-sm-4 col-sm-offset-4 input_wrapper">
			<span class="glyphicon glyphicon-envelope"></span> <span>Email:</span>
			<%= f.email_field :email %>
		</div>
	</div>
	<div class="row">
		<div class="form-group col-sm-4 col-sm-offset-4 input_wrapper">
			<span>Message:</span>
			<%= f.text_area :content, :rows => '10'%>
		</div>
	</div>
	<div class="row" style="text-align: center">
		<%= f.submit 'Send', :class => 'btn btn-primary'%>
	</div>

	<% end %>
</div>

app/views/static_pages/create.html.erb
<div class="thank_wrapper">
	<p>
		Thank you for contacting us. We will get in touch with you very soon.
	</p>
</div>

app/views/static_pages/home.html.erb
<div class="row" style="text-align: center">
	<div class="col-sm-6 new_wrapper">
		<% unless @new_products.nil?%>

		<div class="larger">
			<img src="https://s3.amazonaws.com/primegrind/assets/new.png" alt="new items"/>
		</div>
		<div class="new_content">
			<table>
				<tbody>
					<% @new_products.each do |product| %>
					<tr>
						<td>
						<div class="img_wrapper">
							<%= image_tag product.image.url(:large) %>
						</div></td>
						<td>
						<div class="body">
							<p class="title">
								<%= product.name%>
							</p>
							<p class="med">
								<%= product.desc%>
							</p>
							<p style="text-align: right">
								<%= link_to "Quick Link>>", product_path(product), :class => 'med'%>
							</p>
						</div></td>
					</tr>
					<% end %>
				</tbody>
			</table>
		</div>
		<% end %>
	</div>
	<div class="col-sm-3 special_wrapper">
		<% unless @special_products.nil? %>

		<div class="larger">
			<img src="https://s3.amazonaws.com/primegrind/assets/special.png" alt="special items"/>
		</div>
		<% @special_products.each do |product|%>
		<div class="special_content">
			<p class="bold">
				<%= product.name %>:
			</p>

			<div class="body">
				<p>
					<i><%= product.desc%></i> - <label>$<%unless product.product_details.nil?%><%= product.product_details.first.price%><% end %></label>
				</p>
			</div>
			<p class="bold med">
				Available 7am to 11am
			</p>
			<p>
				<%= link_to "Quick Link>>", product_path(product), :class => "med"%>
			</p>
			<div class="img_wrapper">
				<%= image_tag product.image.url(:large)%>
			</div>
		</div>
		<% end %>
		<div class="larger" style="position: relative">
			<div class="sci_wrapper">
				<img src="https://s3.amazonaws.com/primegrind/assets/scissors.jpg" alt=""/>
			</div>
			<img src="https://s3.amazonaws.com/primegrind/assets/coupon.png" id="coupon" alt="coupon"/>
		</div>
		<div class="coupon_wrapper">
			<table>
				<tbody>
					<tr>
						<td>
						<div class="img_wrapper">
							<img src="https://s3.amazonaws.com/primegrind/assets/logo.jpg"/>
						</div></td>
						<td>
						<div class="coupon_content" >
							<p>
								BUY 10 DRINKS
							</p>
							<span class="med">(any size)</span>
							<p>
								GET 1 FREE
							</p>
						</div></td>
					</tr>
				</tbody>
			</table>
			<p class="small">
				Remember to ask for our coupon card and get a stamp on it on your each visit.
			</p>
		</div>
		<% end %>

	</div>

	<div class="col-sm-3 address" style="text-align: left">

		<div class="larger" style="padding-left: 15px">
			<img src="https://s3.amazonaws.com/primegrind/assets/contact.png" alt="contact"/>
		</div>
		<div class="address_content">
			<div class="row border_bottom">
				<span class="glyphicon glyphicon-phone"></span>
				<span>213-477-5633</span>
			</div>
			<div class="row border_bottom">
				<span class="glyphicon glyphicon-envelope"></span>
				<span>primegrind@gmail.com</span>
			</div>
			<div class="row" style="display: inline-block">
				<span class="glyphicon glyphicon-home"></span>

				<span>714 W 1st street</span>

				<div style="padding-left: 30px">
					Los Angeles, Ca 90012
				</div>

				<div style="padding-left: 30px">
					<a href="https://www.google.com/maps/place/714 w 1st street,los angeles,ca 90014"
					target="_blank" style="color: darkred">get direction</a>
				</div>
			</div>
			<div class="map_wrapper row">
				<div id="map_canvas"></div>
			</div>
		</div>
	</div>
</div>