config/routes.rb
Rails.application.routes.draw do

  resources :registrations

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'welcome/index'

  root 'static_pages#home'

  
  get 'static_pages/aboutus'
  get 'static_pages/contactus'
  post 'static_pages/create'
  get 'password_resets/new'
  get 'password_resets/edit'
  get 'sessions/new'
  post 'categories/search'
  get 'categories/index'

  get 'contact' => 'static_pages#contactus'
  get 'aboutus' => 'static_pages#aboutus'
  post 'contact' => 'static_pages#create'
  post 'results' => 'categories#search'
  get 'results' => 'categories#index'
  resources :categories
  resources :products

  resources :cart do
    collection do
      get 'checkout'
      get 'set'
    end
  end

  resources :users do
    resources :addresses
    resources :orders
  end

  resources :payments

  get 'signup'  => 'users#new'
  get 'account' => 'users#show'
  get 'update' => 'users#edit'

  post "/hook" => "orders#hook"
  post "/users/:user_id/orders/:id" => 'orders#index'

  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  resources :contact, only: [:create]
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :remember_token, :activation_token, :reset_token
  before_create :create_activation_digest
  before_save {self.email = email.downcase}

  has_many :addresses, dependent: :destroy
  has_many :orders, dependent: :destroy
   
  accepts_nested_attributes_for :addresses
  
  validates :email, presence: true, uniqueness: true, length: {maximum: 255}
  validates :name, presence: true, length: {minimum: 2}, length: {maximum: 50}

  has_secure_password
  validates :password, presence: true, length: {in: 6..20}
    
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
  
  def User.new_token
    SecureRandom.urlsafe_base64
  end
  
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end
  
  def authenticated?(attribute, token)
    digest = self.send("#{attribute}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end
  
  def forget
    update_attribute(:remember_digest, nil)
  end
  
  def activate
     update_attribute(:activated, true)
     update_attribute(:activated_at, Time.zone.now)
  end
  
  def send_activation_email
    UserMailer.account_activation_email(self).deliver
  end
  
  def send_welcome_email
    UserMailer.welcome_email(self).deliver
  end
  
  def create_reset_digest
    self.reset_token = User.new_token
    update_attribute(:reset_digest, User.digest(reset_token))
    update_attribute(:reset_sent_at, Time.zone.now)
  end
  
  def send_reset_email
    UserMailer.password_reset_email(self).deliver
  end
  
  def password_reset_expired?
    reset_sent_at < 2.hours.ago
  end

  private
  def create_activation_digest
    self.activation_token = User.new_token
    self.activation_digest = User.digest(activation_token)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_filter :verify_authenticity_token
  before_action :logged_in_user, only: [:edit, :update, :show]
  before_action :correct_user,   only: [:edit, :update, :show]

  def new
    @title = "Sign Up"
    redirect_to account_path(:id => @current_user.id) if logged_in?

    @user = User.new
    @address = @user.addresses.build
  end

  def create
    @user = User.new(user_params)
    @address = @user.addresses.build(address_params)

    if @user.save
      #log_in @user
      @user.send_activation_email
      flash[:info] = "Please check your email to activate your account."
      redirect_to root_url
    else
      render 'new'
    end
  end

  def show
    @title = "My Account"
    if @current_user.addresses.find_by(:default => true).nil?
      @address = @current_user.addresses.first
      @address.update(:default => true)
    end
    @phone = @current_user.addresses.find_by(:default => true).phone

  end

  def edit
    @title = "Update My Profile"
    @user = @current_user
  end

  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      flash[:success] = "Successfully Updated."
      redirect_to account_path(:id => @user.id)
    else
      render 'edit'
    end

  end

  def logged_in_user
    unless logged_in?
      store_location
      redirect_to login_path
    end
  end

  def correct_user
    if User.where(:id => params[:id]).blank?
      redirect_to root_url
    else
      user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(user)
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :name, :password, :password_confirmation, :subscribe)
  end

  private

  def address_params
    params[:user].require(:address).permit(:address1, :address2, :city, :zip, :phone)
  end

end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user, options)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/users/_show.html.erb
<div style="text-align: left">
	<label>Welcome, <%= @current_user.name%></label>
</div>
<div class="row" style="width: 100%">
	<div class="col-sm-5 div_border">
		<table id="info">
			<tr>
				<td>Email: </td>
				<td><%= @current_user.email %></td>
			</tr>
			<tr>
				<td>Phone: </td>
				<td><%= @phone %></td>
			</tr>
		</table>
		<div class="btn_wrapper">
			<%= link_to 'Update Profile', update_path(:id => @current_user.id), :class => 'btn bg-warning btn-sm'%>
		</div>
	</div>
</div>
<div style="text-align: left; margin-top: 10px; position: relative">
	<label><span class="glyphicon glyphicon-home"></span> Address</label>
	<a href="" data-toggle="modal" data-target="#newAddressModal" id="new_address" class="text-success"><span class="glyphicon glyphicon-plus"></span></a>
</div>

<div class="row" style="width: 100%">

	<% @current_user.addresses.each do |address|%>
	<div class="col-sm-5 div_border">
		<h5 style="font-weight: bold"><%= address.name %></h5>

		<div>
			<%= address.address1 %>
			<%= address.address2 %>
		</div>
		<div>
			<%= address.city %>, CA
			<%= address.zip %>
		</div>
		<div style="font-weight: bold">
			<%= address.phone %>
		</div>
		<div class="btn_wrapper">
			<%= link_to 'Update', edit_user_address_path(@current_user.id, address), :class => 'btn bg-warning btn-sm update' %>
			<%= link_to 'Delete', user_address_path(@current_user.id, address), :method => :delete, :class => 'btn bg-warning btn-sm' %>
		</div>
	</div>
	<% end %>
</div>

<%= render 'addresses/new'%>

app/views/users/edit.html.erb
<%= form_for :user, :html => {:class => "form-horizontal", :role => "form"}, url: user_path(@user), method: :patch do |user| %>
<div class="scrollable"></div>
<div class="row">
	<div class="col-sm-4 col-sm-offset-4">
		<%= render 'shared/error_msgs', obj: @user%>
	</div>
</div>
<div class="form-group">
	<%= user.label(:name, "Full Name:  ", class: 'control-label col-sm-4', for: 'name')  %>
	<div class="col-sm-4">
		<%= user.text_field :name, class: 'form-control' %>
	</div>
</div>
<div class="form-group">
	<%= user.label(:password, "Password: ", class: 'control-label col-sm-4', for: 'password')  %>
	<div class="col-sm-4">
		<%= user.password_field :password, class: 'form-control' %>
	</div>
</div>
<div class="form-group">
	<%= user.label(:password_confirmation, "Confirm Password: ", class: 'control-label col-sm-4', for: 'password_confirm')  %>
	<div class="col-sm-4">
		<%= user.password_field :password_confirmation, class: 'form-control' %>
	</div>

</div>

<div class="form-group">
	<div class="col-sm-4 col-sm-offset-4">
		<button type="submit" class="btn btn-primary btn-sm">
			Update
		</button>
		<%= link_to 'Cancel', account_path(:id => @current_user.id), :class => 'btn btn-primary btn-sm'%>
	</div>
</div>

<% end %>

app/views/users/new.html.erb
<%= form_for @user, :html => {:class => "form-horizontal", :role => "form"}, url: users_path do |user| %>

<div class="row">
	<div class="col-sm-4 col-sm-offset-4">
		<%= render 'shared/error_msgs', obj: @user%>
	</div>
</div>
<div class="form-group">
	<%= user.label :email, "Email: ", :class => 'control-label col-sm-4', for: 'email'  %>
	<div class="col-sm-4">
		<%= user.email_field :email, :autofocus => true, class: 'form-control' %>
	</div>

</div>
<div class="form-group">
	<%= user.label(:password, "Password: ", class: 'control-label col-sm-4', for: 'password')  %>
	<div class="col-sm-4">
		<%= user.password_field :password, class: 'form-control' %>
	</div>
</div>
<div class="form-group">
	<%= user.label(:password_confirmation, "Confirm Password: ", class: 'control-label col-sm-4', for: 'password_confirm')  %>
	<div class="col-sm-4">
		<%= user.password_field :password_confirmation, class: 'form-control' %>
	</div>

</div>
<div class="form-group">
	<%= user.label(:name, "Full Name:  ", class: 'control-label col-sm-4', for: 'name')  %>
	<div class="col-sm-4">
		<%= user.text_field :name, class: 'form-control' %>
	</div>
</div>

<%= user.fields_for(@address) do |address| %>
<%= render 'addresses/address_fields', f: address, name: false %>
<% end %>

<div class="form-group" >
	<div class="col-sm-4 col-sm-offset-4" style="">
		<%= user.label :subscribe, class: "checkbox inline" do %>
		<%= user.check_box :subscribe %>
		<span>Subsribe to our mailing list</span>
		<% end %>
	</div>
</div>

<%= user.submit "Create my account", class: 'btn btn-primary' %>

<% end %>

app/views/users/show.html.erb
<div class="account_wrapper">
	<div class="row account_info" style="width: 50%; min-width: 250px; padding: 5px">
		<div style="text-align: left">
			<label><span class="glyphicon glyphicon-user"></span> Welcome, <%= @current_user.name%></label>
		</div>
		<div class="div_border">
			<table id="info">
				<tr>
					<td>Email: </td>
					<td><%= @current_user.email %></td>
				</tr>
				<tr>
					<td>Phone: </td>
					<td><%= ActiveSupport::NumberHelper.number_to_phone(@phone, area_code: true) %></td>
				</tr>
			</table>
			<div class="btn_wrapper">
				<%= link_to 'Update Profile', update_path(:id => @current_user.id), :class => 'btn btn-primary btn-sm'%>
			</div>
		</div>
	</div>

	<div class="row" style="">
		<div style="text-align: left; margin-top: 10px; position: relative">
			<label><span class="glyphicon glyphicon-home"></span> Address</label>
			<%= link_to '<span class="glyphicon glyphicon-plus-sign"></span>'.html_safe, new_user_address_path(:user_id => @current_user.id), :class => 'text-primary'%>
		</div>
		<table style="width: 100%">
			<tbody>
				<% addresses = @current_user.addresses%>
				<% $i = 0 %>
				<% while $i <= addresses.size()-1 do%>
				<% address = addresses[$i]%>

				<tr>
					<td style="padding: 5px">
					<div class="div_border">
						<h5 style="font-weight: bold"><%= address.name %></h5>
						<div>
							<%= address.address1 %>
							<%= address.address2 %>
						</div>
						<div>
							<%= address.city %>, CA
							<%= address.zip %>
						</div>
						<div style="font-weight: bold">
							<%= ActiveSupport::NumberHelper.number_to_phone(address.phone, area_code: true) %>
						</div>
						<div class="btn_wrapper">
							<%= link_to 'Update', edit_user_address_path(@current_user.id, address), :class => 'btn btn-primary btn-sm update' %>
							<%= link_to 'Delete', user_address_path(@current_user.id, address), :method => :delete, :class => 'btn btn-primary btn-sm' %>
						</div>
					</div></td>

					<% unless addresses[$i+1].nil? %>
					<% address = addresses[$i+1]%>
					<% $i = $i+1%>

					<td style="padding: 5px">
					<div class="div_border">
						<h5 style="font-weight: bold"><%= address.name %></h5>
						<div>
							<%= address.address1 %>
							<%= address.address2 %>
						</div>
						<div>
							<%= address.city %>, CA
							<%= address.zip %>
						</div>
						<div style="font-weight: bold">
							<%= ActiveSupport::NumberHelper.number_to_phone(address.phone, area_code: true) %>
						</div>
						<div class="btn_wrapper">
							<%= link_to 'Update', edit_user_address_path(@current_user.id, address), :class => 'btn btn-primary btn-sm update' %>
							<%= link_to 'Delete', user_address_path(@current_user.id, address), :method => :delete, :class => 'btn btn-primary btn-sm' %>
						</div>
					</div></td>
					<% else %>
					<td style="width: 50%">
						
					</td>
					<% end %>
					<% $i += 1%>
				</tr>
				<% end %>
			</tbody>
		</table>

	</div>
</div>