config/routes.rb
Rails.application.routes.draw do

  resources :registrations

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'welcome/index'

  root 'static_pages#home'

  
  get 'static_pages/aboutus'
  get 'static_pages/contactus'
  post 'static_pages/create'
  get 'password_resets/new'
  get 'password_resets/edit'
  get 'sessions/new'
  post 'categories/search'
  get 'categories/index'

  get 'contact' => 'static_pages#contactus'
  get 'aboutus' => 'static_pages#aboutus'
  post 'contact' => 'static_pages#create'
  post 'results' => 'categories#search'
  get 'results' => 'categories#index'
  resources :categories
  resources :products

  resources :cart do
    collection do
      get 'checkout'
      get 'set'
    end
  end

  resources :users do
    resources :addresses
    resources :orders
  end

  resources :payments

  get 'signup'  => 'users#new'
  get 'account' => 'users#show'
  get 'update' => 'users#edit'

  post "/hook" => "orders#hook"
  post "/users/:user_id/orders/:id" => 'orders#index'

  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  resources :contact, only: [:create]
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]

end

app/models/payment.rb
require 'net/http'
require 'uri'

class Payment < ActiveRecord::Base
  MERCHANT_ID = "100001"
  INTEGRATION_URL = "https://gateway.cardstream.com/direct/"
  attr_accessor :cardNumber, :cardCVV, :cardExpiryMonth, :cardExpiryYear
  
  validate :credit_card_api_access, :on => :create
  def request_data
    {
      :amount => self.amount.to_i,
      :cardNumber => self.cardNumber,
      :cardExpiryMonth => self.cardExpiryMonth.to_i,
      :cardExpiryYear => self.cardExpiryYear.to_i,
      :cardCVV => self.cardCVV.to_i,
      :merchantID => MERCHANT_ID,
      :action => "SALE",
      :type => 1,
      :currencyCode => 826,
      :orderRef => "Test purchase",
      :countryCode => 826,
      :returnInternalData => "Y",
      :threeDSRequired => "N"
    }
  end

  def credit_card_api_access
    uri = URI.parse(INTEGRATION_URL)
    http = Net::HTTP.new(uri.host, 443)
    http.use_ssl = true
    req = Net::HTTP::Post.new(uri.request_uri)
    req.set_form_data(request_data)
    response = http.request(req)
    response_hash = Rack::Utils.parse_nested_query response.body
    if response_hash['responseCode'] != "0"
      errors.add(:id, "Payment failed #{response_hash['responseMessage']}")
    else
      self.attributes = strip_cc_response_hash(response_hash)
    end

    def strip_cc_response_hash(hsh)
      hsh.each { |key,value| hsh.delete(key) unless Payment.column_names.include?(key)}
      return hsh
    end
  end
end

app/models/payment_type.rb
class PaymentType < ActiveRecord::Base
  has_many :orders
end

app/controllers/payments_controller.rb
class PaymentsController < InheritedResources::Base
  def new
    @payment = Payment.new
  end

  private

  def payment_params
    params.require(:payment).permit(:amount, :responseCode, :responseMessage, :amountReceived, :cardNumberMask,
    :cardType, :cardTypeCode, :responseCode, :transactionID, :xref, :cardNumber,
    :cardCVV, :cardExpiryMonth, :cardExpiryYear)
  end
end

app/helpers/payments_helper.rb
module PaymentsHelper
  def cc_years
    yrs = []
    year_today = Date.today.strftime("%y").to_i
    year_today.upto(year_today+10).each do |y| yrs << y.to_s;end
    return yrs
  end

  def cc_months
    ['01','02','03','04','05','06','07','08','09','10','11','12']
  end
end

app/views/payments/_form.html.erb
<%= form_for(@payment) do |f| %>
  <% if @payment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@payment.errors.count, "error") %> prohibited this payment from being saved:</h2>

      <ul>
      <% @payment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :amount %><br>
    <%= f.text_field :amount %>
  </div>
  <div class="field">
    <%= f.label :responseCode %><br>
    <%= f.number_field :responseCode %>
  </div>
  <div class="field">
    <%= f.label :responseMessage %><br>
    <%= f.text_field :responseMessage %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/payments/edit.html.erb
<h1>Editing payment</h1>

<%= render 'form' %>

<%= link_to 'Show', @payment %> |
<%= link_to 'Back', payments_path %>

app/views/payments/index.html.erb
<h1>Listing payments</h1>

<table>
  <thead>
    <tr>
      <th>Amount</th>
      <th>Responsecode</th>
      <th>Responsemessage</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @payments.each do |payment| %>
      <tr>
        <td><%= payment.amount %></td>
        <td><%= payment.responseCode %></td>
        <td><%= payment.responseMessage %></td>
        <td><%= link_to 'Show', payment %></td>
        <td><%= link_to 'Edit', edit_payment_path(payment) %></td>
        <td><%= link_to 'Destroy', payment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Payment', new_payment_path %>

app/views/payments/new.html.erb
<% if @payment != nil && @payment.errors.any? %>
<div class="alert alert-error">
	<a class="close" data-dismiss="alert">×</a>
	<% for message in @payment.errors.full_messages %>
	<%= message %>
	<% end %>
</div>
<% end %>
<% model_class=Payment %>
<div class="page-header">
	<h1><%= t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human %></h1>
</div>

<%= form_for @payment, :html => { :class => 'form-horizontal' } do |f| %>

<div class="control-group">
	<%= f.label :amount, 'Price', :class => 'control-label' %>
	<div class="controls">
		<%= f.text_field :amount, :class => 'text_field' %>
	</div>
</div>

<div class="control-group">
	<%= f.label :cardNumber,'Card Number', :class => 'control-label' %>
	<div class="controls">
		<%= f.text_field :cardNumber, :class => 'text_field' %>
	</div>
</div>

<div class="control-group">
	<%= f.label :cardCVV,'CVV', :class => 'control-label' %>
	<div class="controls">
		<%= f.text_field :cardCVV, :class => 'text_field' %>
	</div>
</div>

<div class="control-group">
	<%= f.label :cardExpiryMonth,'Expiry Month', :class => 'control-label' %>
	<div class="controls">
		<%= f.select(:cardExpiryMonth, options_for_select(cc_months)) %>
	</div>
</div>

<div class="control-group">
	<%= f.label :cardExpiryYear,'Expiry Year', :class => 'control-label' %>
	<div class="controls">
		<%= f.select(:cardExpiryYear, options_for_select(cc_years)) %>
	</div>
</div>

<div class="form-actions">
	<%= f.submit nil, :class => 'btn btn-primary' %>
	<%= link_to t('.cancel', :default => t("helpers.links.cancel")),
	payments_path, :class => 'btn' %>
</div>
<% end %>

app/views/payments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Amount:</strong>
  <%= @payment.amount %>
</p>

<p>
  <strong>Responsecode:</strong>
  <%= @payment.responseCode %>
</p>

<p>
  <strong>Responsemessage:</strong>
  <%= @payment.responseMessage %>
</p>

<%= link_to 'Edit', edit_payment_path(@payment) %> |
<%= link_to 'Back', payments_path %>