config/routes.rb
Rails.application.routes.draw do

  resources :registrations

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'welcome/index'

  root 'static_pages#home'

  
  get 'static_pages/aboutus'
  get 'static_pages/contactus'
  post 'static_pages/create'
  get 'password_resets/new'
  get 'password_resets/edit'
  get 'sessions/new'
  post 'categories/search'
  get 'categories/index'

  get 'contact' => 'static_pages#contactus'
  get 'aboutus' => 'static_pages#aboutus'
  post 'contact' => 'static_pages#create'
  post 'results' => 'categories#search'
  get 'results' => 'categories#index'
  resources :categories
  resources :products

  resources :cart do
    collection do
      get 'checkout'
      get 'set'
    end
  end

  resources :users do
    resources :addresses
    resources :orders
  end

  resources :payments

  get 'signup'  => 'users#new'
  get 'account' => 'users#show'
  get 'update' => 'users#edit'

  post "/hook" => "orders#hook"
  post "/users/:user_id/orders/:id" => 'orders#index'

  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  resources :contact, only: [:create]
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>PrimeGrind</title>
		<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
		<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
		<%= csrf_meta_tags %>
		<script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
		<script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>
	</head>
	<body>
		<% @categories = Array.new %>
		<% Category.all.order('id ASC').each do |cat| %>
		<% unless cat.name.include?("New") || cat.name.include?("Special") %>
		<% @categories.push(cat) %>
		<% end %>

		<% end %>
		<div id="checker" hidden></div>

		<div class="menu_wrapper row" >
			<table class="right_top_wrapper" style="width: 100%">
				<tbody>
					<tr>
						<td class="menu">
						<div class="ul_wrapper transparent">
							<div class="logo">
								<img src="https://s3.amazonaws.com/primegrind/assets/logo.png" alt="Logo"/>
							</div>
							<ul>
								<li>
									<div class="larger">
										<img src="https://s3.amazonaws.com/primegrind/assets/product.png" alt="Our Products" />
									</div>
								</li>
								<% @categories.each do |category|%>
								<li>
									<%= link_to '<span class="glyphicon glyphicon-circle-arrow-right"></span>'.html_safe + category.name.downcase, category_path(category), :class => "#{current_path(category_path(category))}" %>
								</li>
								<% end %>
							</ul>
						</div></td>
						<td class="right_side">
						<div class="social row">
							<table>
								<tbody>
									<tr>
										<td><a href="https://mbasic.facebook.com/PrimeGrind" target="_blank">
										<div class="wrapper">
											<div class="item white center">
												fb
											</div>
										</div> </a></td>
										<td><a href="https://instagram.com/belac_kab77" target="_blank">
										<div class="wrapper">
											<div class="item white center">
												in
											</div>
										</div> </a></td>
									</tr>
								</tbody>
							</table>
						</div>
						<div class="row">
							<table>
								<tbody>
									<tr>
										<td class="layer_sm" alt="Layer"><img src="https://s3.amazonaws.com/primegrind/assets/layer_sm.png" /></td>
										<td class="td_top">
										<table class="top_wrapper row">
											<Tr>
												<td class="border-right">
												<div class="link">
													<%= link_to '<span class="glyphicon glyphicon-home"> HOME</span>'.html_safe, root_path, :class => "#{is_home}" %>
												</div></td>
												<td class="border-right">
												<div class="link">
													<%= link_to '<span class="glyphicon"> ABOUT US</span>'.html_safe, aboutus_path, :class => current_path_2(aboutus_path) %>
												</div></td>
												<td class="border-right">
												<div class="link">
													<ul>
														<li class="dropdown">
															<a class="dropdown-toggle" data-toggle="dropdown" href="#"><span class="glyphicon glyphicon-menu-hamburger"> PRODUCTS</span> </a>
															<ul class="dropdown-menu">
																<% @categories.each do |category|%>
																<li style="padding: 2px">
																	<%= link_to '<span class="glyphicon glyphicon-circle-arrow-right"> '.html_safe + category.name + '</span>'.html_safe, category_path(category) %>
																</li>
																<% end %>
															</ul>
														</li>
													</ul>
												</div></td>
												<td>
												<div class="link">
													<%= link_to '<span class="glyphicon glyphicon-envelope"> CONTACT US</span>'.html_safe,  contact_path, :class => current_path_2(contact_path)%>
												</div></td>
											</Tr>
										</table></td>
									</tr>
								</tbody>
							</table>
						</div>
						<div class="row title_wrapper transparent padding_left">
							~ <img src="https://s3.amazonaws.com/primegrind/assets/title_skinny.png" alt="" /> ~
						</div>
						<div class="account row transparent">
							<ul>
								<% if logged_in?%>
								<li class="dropdown">
									<a class="dropdown-toggle" data-toggle="dropdown" href="#"> My Account <span class="caret"></span> </a>
									<span style="color: grey">|</span> <%= link_to "Log out", logout_path, method: :delete %>

									<ul class="dropdown-menu">
										<li>
											<%= link_to '<span class="glyphicon glyphicon-user"></span> My Account'.html_safe, account_path(:id => @current_user.id) %>
										</li>
										<li class="divider"></li>
										<li>
											<%= link_to '<span class="glyphicon glyphicon-th-list"></span> Order History'.html_safe, user_orders_path(@current_user) %>
										</li>
										<li class="divider"></li>
										<li>
											<%= link_to "<span class='glyphicon glyphicon-log-out'></span> Log out".html_safe, logout_path, method: :delete %>
										</li>
									</ul>
								</li>
								<% else %>
								<li>
									Welcome to PRIMEGRIND. <%= link_to 'Join', signup_path %> <span style="color: grey">|</span> <%= link_to 'Sign In', login_path %>
								</li>
								<% end %>
							</ul>
						</div>
						<div class="row layer_top">
							<img src="https://s3.amazonaws.com/primegrind/assets/layer.png" alt=""/>
						</div></td>
					</tr>
					<tr>
						<div class="search_wrapper transparent absolute_right">
							<div>
								<%= form_for(:search, :url => results_path) do |f|%>
								<%= f.text_field :value, {:placeholder => 'Search PRIMEGRIND'}%>
								<%= f.button '<span class="line">|</span><span class="glyphicon glyphicon-search"></span>'.html_safe, {:type => 'submit'}%>
								<% end %>
							</div>
						</div>
					</tr>
				</tbody>
			</table>
			<div class="row header">
				<table>
					<tbody>
						<tr>
							<td class="layer_bottom">
							<div class="row">
								<img src="https://s3.amazonaws.com/primegrind/assets/layer_black.png" alt=""/>
							</div></td>
							<td id="header_td" class="padding_top">
							<div class="header_wrapper row" style="padding-bottom: 2px">
								<div class="col-sm-4 col-sm-offset-4">
									<% if @title != nil %>
									<div class="caption margin_right row">
										<%= @title%>
									</div>
									<% end %>
								</div>
								<div class="col-sm-4 cart_link">
									<ul>
										<li class="dropdown">
											<% n = n_cart%>
											<% cart %>

											<% if @total == del_fee || @total.nil?%>
											<% @total = '0.00'%>
											<% end %>

											<%= link_to ('<span class="glyphicon glyphicon-shopping-cart"></span> My Cart&nbsp;&nbsp;$<span id="total">' + @total.to_s + '</span><span class="n_wrapper">&nbsp;(<span id="n">' + n + ')</span>').html_safe, cart_index_url, {:class => 'mycart', 'data-n' => n} %>
												<ul class="dropdown-menu">
													<li>
														<div class="cart_dropdown">
															<div class="pg_wrapper">
																<ul class="pagination pagination-sm">

																</ul>
															</div>

															<table id="cart_dropdown">
																<tbody>
																	<% if @product_details != nil && @product_details.size() > 0 %>
																	<% @product_details.each do |detail| %>
																	<% detail_obj = detail["detail"] %>
																	<tr class="item" data-id=<%= detail_obj.id%>>
																		<td>
																		<div class="img_wrapper">
																			<%= image_tag(detail_obj.product.image.url(:med))%>
																		</div></td>
																		<td>
																		<button type="button" class="remove" style="border: 1px solid lightgrey; float: right">
																			&times;
																		</button>
																		<div class="price">
																			$<%= detail_obj.price %>
																		</div>
																		<div class="title">
																			<%= detail_obj.product.name %>
																		</div>
																		<div class="size">
																			<% if detail_obj.size != nil%>
																			(<%= detail_obj.size.name %>)
																			<% else %>
																			(One Size)
																			<% end %>
																		</div>
																		<div class="qty">
																			Qty <%= detail["qty"]%>
																		</div> <% ext_arr = detail["extra"] %>
																		<div class="extra">
																			<% if ext_arr.size() != 0%>

																			<% ext_arr.each do |ext_id|%>
																			<% ext_obj=ExtraProduct.find(ext_id)%>
																			<div class="ext" data-price=<%= ext_obj.price%>>
																				<%= ext_obj.name%>
																			</div>
																			<% end %>
																			<% end %>
																		</div></td>
																	</tr>
																	<% end %>
																	<% end %>

																	<tr>
																		<td>
																		<div class="total">
																			Total:
																		</div></td>
																		<td>
																		<div class="hidden_values" hidden>
																			<div class="tax">
																				<%= tax%>
																			</div>
																			<div class="del_fee">
																				<%= del_fee%>
																			</div>
																		</div>
																		<div class="total">
																			$<%= @total%>
																		</div></td>
																	</tr>
																	<tr>
																		<td>
																		<div class="btn_wrapper">
																			<%= link_to 'View Cart', cart_index_path , :class => 'btn btn-sm btn-warning'%>
																		</div></td>
																		<td>
																		<div class="btn_wrapper">
																			<% if @current_user != nil %>
																			<%= link_to 'Pay Now',  new_user_order_path(@current_user, @order), :class => 'btn btn-sm btn-primary'%>
																			<% else%>
																			<%= link_to 'Pay Now',  new_user_order_path(0, @order), :class => 'btn btn-sm btn-primary'%>
																			<% end %>
																		</div></td>
																	</tr>
																</tbody>
															</table>
														</div>
													</li>
												</ul>
										</li>
									</ul>
								</div>
							</div></td>
						</tr>
					</tbody>
				</table>
			</div>
		</div>
		<div class="content row">

			<% flash.each do |key, value| %>
			<% if key == "success"%>
			<div class="bg-success text-success flash_style">
				<%= content_tag :div, value, class: "flash #{key}" %>
			</div>
			<% end%>

			<% if key == "danger"%>
			<div class="bg-danger text-danger flash_style">
				<%= content_tag :div, value, class: "flash #{key}" %>
			</div>
			<% end %>

			<% if key == "info"%>
			<div class="bg-info text-info  flash_style">
				<%= content_tag :div, value, class: "flash #{key}" %>
			</div>
			<% end %>

			<% end %>
			<div style="margin-top: 20px">
				<%= yield %>
			</div>
		</div>
		</div>
		<div class="row bottom dark center">
			We accept all major Credit Card/Debit Card/Paypal
			<div>
				<img src="https://s3.amazonaws.com/primegrind/assets/credit-card-logos.png"/>
			</div>
			<div id="copyright">
				© Copyright 2015 - All rights reserved
			</div>
		</div>
	</body>
</html>